### ISSUE TITLE
help / documentation plugins

### ISSUE THREAD

**Issue by obeyler** [bitnami/bitnami-docker-elasticsearch#62]
I try to use bitnami helm chart for elasticsearch and fluentd 
I see that fluentd need to install a plugin into elasticsearch. (https://github.com/uken/fluent-plugin-elasticsearch#installation) but it use gem

Is there a list of plugin witch can be use (tested or not) ?
 
 I see on the value.yaml file this but It's not clear for me what can it be set
could you provide a sample ?

   ## Comma, semi-colon or space separated list of plugins to install at initialization
      ## ref: https://github.com/bitnami/bitnami-docker-elasticsearch#environment-variables
      ##
      plugins:

**Comment by andresbono** [comment]
Hi @obeyler,

Here you have all the information about Elasticsearch plugins: https://www.elastic.co/guide/en/elasticsearch/plugins/7.0/intro.html.

The piece of code that reads the list of plugins provided as an environment variable is the following:

https://github.com/bitnami/bitnami-docker-elasticsearch/blob/399c57fbe82da43f107056520b7bd2a9966baff4/7/debian-9/rootfs/libelasticsearch.sh#L406-L427

An example of usage could be the following:

```
$ docker run --name elastic --rm -d -e ELASTICSEARCH_PLUGINS=analysis-icu,ingest-attachment bitnami/elasticsearch:latest
57c4064ebf512b51c45dda0a88bd8a2dfa817a38d3b8a1766ea413e2c75b6653

$ docker exec -it elastic elasticsearch-plugin list
analysis-icu
ingest-attachment
```

However, I don't know if this information is useful for you, as the fluentd plugin is installed with `gem install` instead of using the elasticsearch plugin management tool.
