### ISSUE TITLE
Question - Elasticsearch Java Dependency

### ISSUE THREAD

**Issue by aaditya-panik** [bitnami/bitnami-docker-elasticsearch#69]
Hi,

I'm not sure if this is the right place to ask this question, but is there any dependency for ElasticSearch via docker on Java on the **host machine**? I would love it if I could be pointed to some external resources explaining this further. Thanks!

**Comment by andresbono** [comment]
Hi @aaditya-panik, the Bitnami Docker container includes Elasticsearch, Java and some system packages

https://github.com/bitnami/bitnami-docker-elasticsearch/blob/7c6b3201016ff62b5edfed64b2878418256eb5d2/7/debian-9/Dockerfile#L12-L14

These artifacts are stored in the container image and they are isolated from the host machine.

In order to run Elasticsearch, you will need hardware resources from the host machine and there are some Kernel settings that need to be valid:

https://github.com/bitnami/bitnami-docker-elasticsearch/blob/f08b21203812d4521d380b26c410e4b338b3a077/6/debian-9/rootfs/libelasticsearch.sh#L195-L197

I'm not sure if I'm understanding your question. Let me know if so.

**Comment by aaditya-panik** [comment]
Hi @andresbono, Thanks for the information. This does answer my question partially but I wanted to know if the ES container I run on Docker has dependencies on **any** Java components (JDK, JRE, etc.)  from the host machine on which the Docker daemon is running? My use case is such that we wanted to remove all Java components from the host machine without affecting the containers.

According to what I have found along with the information you have shared, it doesn't look like it does. But regardless, I just wanted to confirm it.

**Comment by andresbono** [comment]
Hi @aaditya-panik, you can safely remove Java components from the host machine and the Elasticsearch container won't by affected by that.
