### ISSUE TITLE
Idempotency of plugins to be installed 

### ISSUE THREAD

**Issue by jbianquetti-nami** [bitnami/bitnami-docker-elasticsearch#80]
**Description**

Idempotency of plugins

You can define a set of plugins to be installed via env vars. But if you install some plugin at some point and later on, you remove that plugin from the list, the plugin is still installed in the PVC.

What I'm asking for is: we do should obey the ELASTICSEARCH_PLUGINS env var or respect the plugins existing on the persisted volume like manually installed plugins?

I see pros and cons on both cases 

**Steps to reproduce the issue:**

Add a plugin to the ELASTICSEARCH_PLUGINS env var
Plugin is installed
Remove a plugin from the ELASTICSEARCH_PLUGINS env var
???

**Describe the results you expected:**

If the only/preferred way to manage plugins is via  ELASTICSEARCH_PLUGINS env var, then it should an idempotent operation
BUT this can break manually installed plugins 

**Additional information you deem important (e.g. issue happens only occasionally):**

image-render plugin was installed on the persistent volume and It was not in the env var list. 
This caused the pod failed to start because the image-render crashed avoiding starting the pod because  liveness/readiness probes failures

Fixed by manually removed the plugin from persistent volume

**Version**

All those supporting ELASTICSEARCH_PLUGINS

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

It happened on K8s, but it's likely to happen on docker as well

**Comment by javsalgar** [comment]
Hi,

I see much more risky having the container remove plugins that are not in the list. Maybe we should rename the env var to something that clearly states that the plugins will be installed of first boot in order to avoid confusion. In my opinion, we should respect all the manually installed plugins.

**Comment by jbianquetti-nami** [comment]
Agreed with you: we should support manually installed plugins along with the env var defined. 
+1 on change the env var to something like ELASTICSEARCH_PLUGINS_ON_BOOT and provide the required documentation.

**Comment by fmulero** [comment]
This requests has more than a year and there is no plan to implement it in short term.

We are also moving to [a new repository](https://github.com/bitnami/containers) in order to be aligned with the approach followed in [bitnami/charts](https://github.com/bitnami/charts). More information [here](https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html). If you are still interested on this feature, please open a new issue in [bitnami/containers](https://github.com/bitnami/containers) repository
